# Config.yaml specifies the content and ordering within a repo for a curriculum block

# Supported Fields
# ==========================
# Standards -- (Standards = Units). A list of Units for a block
# Standard.Title: string -- The Unit title that shows up on the curriculum overview
# Standard.UID: string -- A unique ID for the Unit. Use `cmd/ctrl+option/alt+u` to generate (runs once per cursor/selection)
# Standard.Description: string -- The Unit description that shows up on the curriculum overview
# Standard.SuccessCriteria: list -- An array of success criteria that can be viewed when scoring the checkpoint in a Unit.
# Standard.ContentFiles: list -- A list of Lessons and (optional) Checkpoints in a Unit.
# Standard.ContentFiles.Type: Lesson | Checkpoint -- The type of the current content file.
# Standard.ContentFiles.UID: string -- A unique ID for the Unit. Use `cmd/ctrl+option/alt+u` to generate (runs once per cursor/selection)
# Standard.ContentFiles.Path: string -- The absolute path to the Lesson, starting with `/`. Use `cmd/ctrl+option/alt+p` to generate
# Standard.ContentFiles.DefaultVisibility: hidden -- (optional) Set to 'hidden' to hide when a course first starts.
# Standard.ContentFiles.Autoscore: boolean -- (optional, for Checkpoints only) submit checkpoint scores without review
# Standard.ContentFiles.MaxCheckpointSubmissions: number -- (optional, for Checkpoints only) limit the number of submissions

# Related Snippets
# ==========================
# `unityaml`: add a Unit
# `lessonyaml`: add a lesson
# Note: Be sure to place the cursor at the appropriate indentation level before running either of these.

# All UIDs must be unique within a repo. Use `cmd/ctrl+option/alt+u` to generate
Standards:
  - Title: Self Assessment
    UID:  e3b9a942-9bbc-4b1d-9875-2dfe422405f8
    Description: Evaluate your progress after the course 
    SuccessCriteria:
      -  Complete the survey
    ContentFiles:
      - Type: Checkpoint
        UID: 31f01ddf-23dc-4f46-9529-bcccdc93320e
        Path: /post-assessment-survey.md
        Autoscore: false
